### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by arpruss** [Frazew/PythonUSBIP#1]
I am wondering what the license on this code is. Thanks!

**Comment by frazew** [comment]
I would have said Public Domain, but I can't because the USBIP.py source (albeit modified) came from [this repository](https://github.com/lcgamboa/USBIP-Virtual-USB-Device/). For some reason I had ditched the LICENSE file and forgot to add it back. That means all code except the USBIP.py file is Public Domain, the latter being under the FreeBSD License.

**TL;DR**: USBIP.py is FreeBSD License, everything else is Public Domain :)

**Comment by arpruss** [comment]
Thanks!

By the way, would you have any idea why I can't use USBIP.py with a HID descriptor that declares a report ID (e.g., 0x85, 0x04)? If I insert a report ID declaration into a HID descriptor that previously worked with USBIP.py, Windows gives me the message "This device cannot start. (Code 10) Extra end collection found or end collection not found." I've also tried HID descriptors that have worked in Windows (in a hardware device) and if they have report IDs, they give this message, too.

**Comment by frazew** [comment]
It's been a while since I have worked on this project so although I remember running into many issues with descriptors, I no longer remember any of the details...
Don't forget to comment back here if you figure it out so others can see!
